# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monthly_analysis.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'monthly_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16monthly_analysis.proto\"\x88\x02\n\x0fMonthlyAnalysis\x12\x1e\n\x16weekly_completion_rate\x18\x01 \x01(\x02\x12\x39\n\rissue_pattern\x18\x02 \x03(\x0b\x32\".MonthlyAnalysis.IssuePatternEntry\x12\x33\n\nsla_counts\x18\x03 \x03(\x0b\x32\x1f.MonthlyAnalysis.SlaCountsEntry\x1a\x33\n\x11IssuePatternEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x30\n\x0eSlaCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monthly_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONTHLYANALYSIS_ISSUEPATTERNENTRY']._loaded_options = None
  _globals['_MONTHLYANALYSIS_ISSUEPATTERNENTRY']._serialized_options = b'8\001'
  _globals['_MONTHLYANALYSIS_SLACOUNTSENTRY']._loaded_options = None
  _globals['_MONTHLYANALYSIS_SLACOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_MONTHLYANALYSIS']._serialized_start=27
  _globals['_MONTHLYANALYSIS']._serialized_end=291
  _globals['_MONTHLYANALYSIS_ISSUEPATTERNENTRY']._serialized_start=190
  _globals['_MONTHLYANALYSIS_ISSUEPATTERNENTRY']._serialized_end=241
  _globals['_MONTHLYANALYSIS_SLACOUNTSENTRY']._serialized_start=243
  _globals['_MONTHLYANALYSIS_SLACOUNTSENTRY']._serialized_end=291
# @@protoc_insertion_point(module_scope)
