# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: realtime_status.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'realtime_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15realtime_status.proto\"\x84\x01\n\x0eRealtimeStatus\x12\x14\n\x0cpicked_count\x18\x01 \x01(\x05\x12\x15\n\rshipped_count\x18\x02 \x01(\x05\x12\x11\n\tpod_count\x18\x03 \x01(\x05\x12\x17\n\x0f\x63ompletion_rate\x18\x04 \x01(\x02\x12\x19\n\x11\x61vg_delivery_time\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'realtime_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REALTIMESTATUS']._serialized_start=26
  _globals['_REALTIMESTATUS']._serialized_end=158
# @@protoc_insertion_point(module_scope)
