# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monthly_volume_status.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'monthly_volume_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmonthly_volume_status.proto\"\x81\x03\n\x13MonthlyVolumeStatus\x12\x42\n\x10sla_counts_month\x18\x01 \x03(\x0b\x32(.MonthlyVolumeStatus.SlaCountsMonthEntry\x12?\n\x0eweekday_counts\x18\x02 \x03(\x0b\x32\'.MonthlyVolumeStatus.WeekdayCountsEntry\x12\x41\n\x0f\x64istance_counts\x18\x03 \x03(\x0b\x32(.MonthlyVolumeStatus.DistanceCountsEntry\x1a\x35\n\x13SlaCountsMonthEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x34\n\x12WeekdayCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x35\n\x13\x44istanceCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monthly_volume_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONTHLYVOLUMESTATUS_SLACOUNTSMONTHENTRY']._loaded_options = None
  _globals['_MONTHLYVOLUMESTATUS_SLACOUNTSMONTHENTRY']._serialized_options = b'8\001'
  _globals['_MONTHLYVOLUMESTATUS_WEEKDAYCOUNTSENTRY']._loaded_options = None
  _globals['_MONTHLYVOLUMESTATUS_WEEKDAYCOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_MONTHLYVOLUMESTATUS_DISTANCECOUNTSENTRY']._loaded_options = None
  _globals['_MONTHLYVOLUMESTATUS_DISTANCECOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_MONTHLYVOLUMESTATUS']._serialized_start=32
  _globals['_MONTHLYVOLUMESTATUS']._serialized_end=417
  _globals['_MONTHLYVOLUMESTATUS_SLACOUNTSMONTHENTRY']._serialized_start=255
  _globals['_MONTHLYVOLUMESTATUS_SLACOUNTSMONTHENTRY']._serialized_end=308
  _globals['_MONTHLYVOLUMESTATUS_WEEKDAYCOUNTSENTRY']._serialized_start=310
  _globals['_MONTHLYVOLUMESTATUS_WEEKDAYCOUNTSENTRY']._serialized_end=362
  _globals['_MONTHLYVOLUMESTATUS_DISTANCECOUNTSENTRY']._serialized_start=364
  _globals['_MONTHLYVOLUMESTATUS_DISTANCECOUNTSENTRY']._serialized_end=417
# @@protoc_insertion_point(module_scope)
