# Generated by the protocol buffer compiler. DO NOT EDIT!
import sys
import six
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/realtime_status.proto',
  ...
)

class RealtimeStatus(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _realtime_status

    # 클래스의 필드 정의 및 내용
