
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../src:/app/src
      - ../proto:/app/proto
      - ../oauth:/app/oauth
      - ../config:/app/config
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/oauth/google/credentials.json
    ports:
      - "8080:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
